name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: laravel
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: password

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v4
      - name: Копирование .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Установка зависимостей
        run: composer install
      - name: Генерация ключа
        run: php artisan key:generate
      - name: Установка доступов
        run: chmod -R 777 storage bootstrap/cache
      - name: Запуск миграций
        run: php artisan migrate --force
      - name: Запуск Pint
        run: composer pint
      - name: Запуск PHPStan
        run: composer analyse
      - name: Запуск Tests
        run: vendor/bin/phpunit
